spring.application.name=sumup-dashboard-lightweight
sumup.client.id=cc_classic_wc0qQOFbS586f1Ij4uskbd4X9o0XX
sumup.client.secret=cc_sk_classic_DqtX8MdeZ24VkTP9o97yTWO8JdY0BoLXqTt4O3sYhBVFi2nDIK
sumup.redirect.uri=http://localhost:8080/api/sumup/callback
sumup.code=q2IqN8rHjHIYk6EVhIxzSgiPgbHYBaYMmAdS