spring.application.name=sumup-dashboard-lightweight
sumup.client.id=cc_classic_6LE59ub3Qb7u4A2ngubh7COS7SN3C
sumup.client.secret=cc_sk_classic_1OZGNcOg12od7YpxIgUU67NfTCDFFjLaCtl6Re3qeeIHUNfl7K
sumup.redirect.uri=http://localhost:8080/sumup/dashboard
sumup.code=q2IqN8rHjHIYk6EVhIxzSgiPgbHYBaYMmAdS